# Inspiration: https://gist.github.com/NickNaso/0d478f1481686d5bcc868cac06620a60
name: build-and-test
on: [push]
jobs:
  build:
    name: ${{ matrix.config.name }}
    runs-on: ${{ matrix.config.os }}
    strategy:
      fail-fast: false
      matrix:
        config:
        - {
          name: "Windows Latest (MSVC)",
          os: windows-latest,
          build_type: "Release",
          cc: "cl",
          cxx: "cl",
          generator: "Visual Studio 17 2022"
        }
        - {
          name: "MacOS Latest (Clang)",
          os: macos-latest,
          build_type: "Release",
          cc: "clang",
          cxx: "clang++",
          generator: "Xcode"
        }
    steps:
      - uses: actions/checkout@v3
      - name: Configure
        shell: bash
        run: |
          mkdir build
          mkdir install
          cmake \
            -S . \
            -B build \
            -DCMAKE_BUILD_TYPE=${{ matrix.config.build_type }} \
            -G "${{ matrix.config.generator }}" \
            --install-prefix "$(pwd)/install"
      - name: Build
        shell: bash
        run: cmake --build build --config ${{ matrix.config.build_type }}
      - name: Test
        shell: bash
        run: ctest -C ${{ matrix.config.build_type }} --verbose --output-on-failure --test-dir build
